### ISSUE TITLE
Standalone sample page broken

### ISSUE THREAD

**Issue by mscheper** [gitana/alpaca#506]
When I follow the link in the docs to the [standalone sample](http://www.alpacajs.org/demos/alpaca-standalone-sample.html) page, it renders a blank page.

The following errors appear in the console:
```
Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.0.0).
	    at Object.checkRevision (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2693:14)
	    at Object.template (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2709:11)
	    at HandlebarsEnvironment.hb.template (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:196:21)
	    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:583
	    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:277
	    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:314"

15:13:06.210 alpaca-standalone-sample.html:28 Uncaught TypeError: $(...).alpaca is not a function
    at HTMLDocument.<anonymous> (alpaca-standalone-sample.html:28)
    at j (jquery-1.11.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js:2)
    at Function.ready (jquery-1.11.1.min.js:2)
    at HTMLDocument.J (jquery-1.11.1.min.js:2)
```

**Comment by mscheper** [comment]
Apart from needing to update the CDN links, @sblomberg has found a workaround for what I believe is a bug causing this problem. Refer to #507.
