### ISSUE TITLE
alpacajs Not Working : showing blank page when I open below link

### ISSUE THREAD

**Issue by hemantgp** [gitana/alpaca#520]
http://www.alpacajs.org/demos/alpaca-standalone-sample.html

Even I tried with all tutorial (http://www.alpacajs.org/tutorial.html) samples still its same.

**Comment by kfern** [comment]
Do you have any error message in browser console?

**Comment by pepebe** [comment]
Same here:

My console:

Uncaught Exceptiondescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.0.0)."name: "Error"number: undefinedstack: "Error: Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.0.0).↵    at Object.checkRevision (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2693:14)↵    at Object.template (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2709:11)↵    at HandlebarsEnvironment.hb.template (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:196:21)↵    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:583↵    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:277↵    at http://code.cloudcms.com/alpaca/1.5.23/bootstrap/alpaca.min.js:1:314"__proto__: Error
    at Object.exports.__esModule (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2529:24)
    at __webpack_require__ (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:56:30)
    at Object.exports.__esModule (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:2210:19)
    at __webpack_require__ (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:56:30)
    at Object.exports.__esModule (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:157:16)
    at __webpack_require__ (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:56:30)
    at Object.<anonymous> (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:89:17)
    at __webpack_require__ (http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:56:30)
    at http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:76:18
    at http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js:79:10

alpaca-standalone-sample.html:28 Uncaught TypeError: $(...).alpaca is not a function
    at HTMLDocument.<anonymous> (alpaca-standalone-sample.html:28)
    at j (jquery-1.11.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js:2)
    at Function.ready (jquery-1.11.1.min.js:2)
    at HTMLDocument.J (jquery-1.11.1.min.js:2)

**Comment by kfern** [comment]
Hi. 

The error is in the loaded handlebars version. 

Change

`<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.js"></script>
`

by

`<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>`

**Comment by mscheper** [comment]
It's not just the stand-alone version; the basic controls just don't appear in most versions. Here are links to the currently hosted 'registration' example pages for the Web and jQueryUI versions:
- http://www.alpacajs.org/demos/web/registration/index.html
- http://www.alpacajs.org/demos/jqueryui/registration/index.html
These aren't blank, but the basic form features are missing.

I've made some progress trying to get this stuff working (see #506 which is probably the same problem) but it seems Alpaca is basically broken, except for the Bootstrap version. ☹ (And I hate Bootstrap.)
